### ISSUE TITLE
Одно дз - один репозиторий

### ISSUE THREAD

**Issue by coursar** [karysf/horo-coffemat-walls#1]
Нужно разнести домашки по разным репозиториям

**Comment by karysf** [comment]
Нужно в ws разделить на проекты и перезалить или можно как-то иначе?

**Comment by coursar** [comment]
Достаточно сделать это на уровне папок. В самой верхней удалить .git. А дальше для каждой папки - свой репозиторий и свой проекта на GitHub. Но так или иначе для каждого ДЗ придётся формировать свою папку.
